In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier

In [2]:
dataset1=pd.read_csv("wine.csv",index_col=None)
df=dataset1
df = pd.get_dummies(df, drop_first=True)
df

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [3]:
indep_x=df.iloc[:,0:13].values
dep_y=df.iloc[:,13].values

In [4]:
def lda(x_train,y_train,x_test, n):
    lda = LinearDiscriminantAnalysis(n_components=n)
    x_train_lda = lda.fit_transform(x_train, y_train)
    x_test_lda = lda.transform(x_test)
    return x_train_lda,x_test_lda,lda

In [5]:
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size=0.2,random_state=0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train,x_test,y_train,y_test,sc

def cm_prediction(classifier,x_test_lda,y_test):
    y_pred = classifier.predict(x_test_lda)

    cm = confusion_matrix(y_test,y_pred)
    accuracy = accuracy_score(y_test,y_pred)
    report = classification_report(y_test,y_pred)
    return classifier,accuracy

def decision(x_train,y_train,x_test,y_test):
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

In [6]:
def LDA_classification(acclog):
    LDAdataframe = pd.DataFrame(index = ['LDA'], columns = ['decision'])
    LDAdataframe['decision'] = accdec
    return LDAdataframe    

accdec = []

In [7]:
x_train,x_test,y_train,y_test,sc = split_scaler(indep_x,dep_y)

In [8]:
x_train_lda, x_test_lda, lda = lda(x_train,y_train,x_test, 1)

accdec=[]

In [9]:
x_train_lda

array([[ 3.57315552],
       [ 0.85475898],
       [ 0.62173655],
       [ 4.80786412],
       [-3.8579759 ],
       [-3.59455458],
       [-0.53772906],
       [ 0.04058577],
       [ 0.99835348],
       [-3.74095658],
       [ 3.76035226],
       [-0.15106412],
       [ 3.62762899],
       [-3.94229781],
       [ 3.33429017],
       [ 3.90206871],
       [-3.55835472],
       [ 5.63175281],
       [-5.56217254],
       [ 0.23296188],
       [ 5.03141997],
       [ 3.52861651],
       [-1.17815662],
       [ 3.58320131],
       [ 5.21649905],
       [-3.01647841],
       [ 1.86178658],
       [ 3.93816398],
       [-1.0836235 ],
       [ 1.8691488 ],
       [ 3.27717205],
       [-0.47842302],
       [-4.14433134],
       [ 2.45009727],
       [-1.20844631],
       [ 2.55631466],
       [-1.6091476 ],
       [-5.52462148],
       [-2.44685583],
       [-1.95474568],
       [ 5.54394234],
       [ 5.74409562],
       [ 1.13553056],
       [-1.2483554 ],
       [-0.00961488],
       [ 5

In [10]:
x_test_lda

array([[-3.83960313],
       [ 5.24601727],
       [-0.66064228],
       [-2.16667061],
       [-0.16079996],
       [-5.31374258],
       [-4.78386714],
       [ 5.55863966],
       [-1.29772139],
       [ 0.53068371],
       [ 2.36900593],
       [ 5.14502202],
       [-5.27947032],
       [-2.70452577],
       [ 4.32314426],
       [-0.65835601],
       [-4.07332713],
       [-6.55291385],
       [ 2.40020179],
       [-5.14219986],
       [-2.46475469],
       [-2.5190649 ],
       [-1.79798575],
       [-1.43423986],
       [ 1.11433225],
       [ 0.28604133],
       [-1.21198193],
       [ 0.84900431],
       [-1.03105294],
       [ 4.83489722],
       [-4.75464421],
       [-3.33786142],
       [ 1.02045007],
       [-3.1347464 ],
       [-4.25385909],
       [-3.16058359]])

In [11]:
lda

LinearDiscriminantAnalysis(n_components=1)

In [12]:
classifier,accuracy = decision(x_train_lda,y_train,x_test_lda,y_test)
accdec.append(accuracy)

In [13]:
result = LDA_classification(accdec)

In [14]:
result

decision
LDA  0.888889

In [15]:
filename = 'Finalized_Decisiontree_Model.sav'
pickle.dump(classifier,open(filename,'wb'))

In [16]:
filenameSC = 'sc.pkl'
pickle.dump(sc,open(filenameSC,'wb'))
sc = pickle.load(open('sc.pkl','rb'))

In [17]:
filenameLDA = 'lda.pkl'
pickle.dump(lda,open(filenameLDA,'wb'))
lda = pickle.load(open('lda.pkl','rb'))

In [18]:
df.columns

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Customer_Segment'],
      dtype='object')

In [19]:
User_input = ([[14.3,1.71,2.14,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1050]])

In [20]:
scaled_input = sc.transform(User_input)
scaled_input     

array([[ 1.63508058, -0.59617626, -0.84433927, -1.15290415,  1.89709249,
         0.88811832,  1.14228219, -0.65631245,  1.16092829,  0.25075241,
         0.37819941,  1.85216556,  1.01637071]])

In [21]:
lda_input = lda.transform(scaled_input)
lda_input

array([[-5.26244343]])

In [22]:
loaded_model = pickle.load(open('Finalized_Decisiontree_Model.sav','rb'))
Prediction = loaded_model.predict(lda_input)

In [23]:
Prediction

array([1], dtype=int64)