In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.decomposition import KernelPCA
from sklearn.svm import SVC
import pickle

In [2]:
# Data Collection

dataset1=pd.read_csv("wine.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2, drop_first=True)
df2

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [3]:
indep_x=df2.iloc[:,0:13].values
dep_y=df2.iloc[:,13].values

In [4]:
# Train & Test split
x_train, x_test, y_train, y_test = train_test_split(indep_x, dep_y, test_size=0.2, random_state=0)

In [5]:
# Feature Scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [6]:
# Apply Kernel PCA
kpca = KernelPCA(n_components = 4, kernel = 'rbf')
x_train_kpca = kpca.fit_transform(x_train)
x_test_kpca = kpca.transform(x_test)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train_kpca, y_train)

GaussianNB()

In [8]:
# Make Predictions
y_pred = classifier.predict(x_test_kpca)

In [9]:
# Evaluate Performance
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [10]:
print("Best Accuracy for KernelPCA is Naive:", accuracy)

Best Accuracy for KernelPCA is Naive: 1.0


In [11]:
filename = 'Finalized_Naive_Model.sav'
pickle.dump(classifier,open(filename,'wb'))

In [12]:
filenameSC = 'sc.pkl'
pickle.dump(sc,open(filenameSC,'wb'))

In [13]:
filenameKPCA = 'KPCA.pkl'
pickle.dump(kpca,open(filenameKPCA,'wb'))

In [14]:
sc = pickle.load(open('sc.pkl','rb'))
kpca = pickle.load(open('KPCA.pkl','rb'))

In [15]:
User_input = ([[14.3,1.71,2.14,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1050]])

In [16]:
scaled_input = sc.transform(User_input)
scaled_input  

array([[ 1.63508058, -0.59617626, -0.84433927, -1.15290415,  1.89709249,
         0.88811832,  1.14228219, -0.65631245,  1.16092829,  0.25075241,
         0.37819941,  1.85216556,  1.01637071]])

In [17]:
kpca_input = kpca.transform(scaled_input)
kpca_input

array([[-0.44597122, -0.26428155,  0.07102697,  0.08585517]])

In [18]:
loaded_model = pickle.load(open('Finalized_Naive_Model.sav','rb'))
Prediction = loaded_model.predict(kpca_input)

In [19]:
Prediction

array([1], dtype=int64)