In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
import pickle
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")

In [2]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        #X_train, X_test, y_train, y_test = train_test_split(indep_X,dep_Y, test_size = 0.25, random_state = 0)
        
        #Feature Scaling
        #from sklearn.preprocessing import StandardScaler
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)        
        return X_train, X_test, y_train, y_test,sc

In [3]:
def cm_prediction(classifier,x_test_pca,y_test):
    y_pred = classifier.predict(x_test_pca)
    
    cm = confusion_matrix(y_test,y_pred)
    Accuracy = accuracy_score(y_test,y_pred)
    Report = classification_report(y_test,y_pred)
    return classifier,Accuracy

In [4]:
# Data Collection

dataset1=pd.read_csv("wine.csv",index_col=None)
df=dataset1
df= pd.get_dummies(df, drop_first=True)
df

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[178 rows x 14 columns]

In [5]:
indep_x=df.iloc[:,0:13].values
dep_y=df.iloc[:,13].values

In [6]:
# PCA Model Creation
def pca(x_train,x_test,n):
    pca = PCA(n_components = n)
    x_train_pca = pca.fit_transform(x_train)
    x_test_pca = pca.transform(x_test)
    explained_variance = pca.explained_variance_ratio_
    return x_train_pca, x_test_pca, explained_variance, pca

In [7]:
def navie(x_train_pca,y_train,x_test_pca,y_test):
    classifier = GaussianNB()
    classifier.fit(x_train_pca,y_train)
    return cm_prediction(classifier,x_test_pca,y_test)

In [8]:
def pca_classification(accnaiv):
    pcadataframe = pd.DataFrame(index = ['PCA'], columns = ['Naive'])
    pcadataframe['Naive'] = accnaiv
    return pcadataframe

In [9]:
x_train, x_test, y_train, y_test, sc = split_scalar(indep_x,dep_y)

In [10]:
x_train_pca, x_test_pca, explained_variance, pca = pca(x_train,x_test,4)

accnaiv = []

In [11]:
x_train_pca

array([[ 2.12849974e+00, -1.01973208e+00,  8.26209888e-02,
         6.78090471e-01],
       [-2.94812519e+00, -2.54806705e-01,  1.14589113e+00,
        -5.97968964e-01],
       [ 1.91979542e+00,  1.33701156e+00, -4.02244683e-01,
         7.07416420e-01],
       [-2.13337607e+00, -9.45897150e-01,  1.40277015e+00,
         1.39579872e+00],
       [ 2.23680281e+00, -2.26983910e+00, -8.77499126e-01,
         4.36801265e-01],
       [-2.28747076e+00, -1.99359253e-01,  7.97227232e-01,
         1.23396178e+00],
       [-2.97244958e+00, -2.96522642e-01,  9.31504047e-01,
        -1.06705468e+00],
       [ 2.61809796e+00, -7.76070011e-01,  8.30660247e-02,
         2.24081998e-01],
       [-1.04705463e+00, -3.49093326e+00, -1.29203589e+00,
        -8.95933972e-01],
       [ 2.60981596e+00,  7.34569695e-02,  1.78959140e-01,
        -4.93030107e-01],
       [ 1.52296770e-01,  2.31809388e+00,  4.97096689e-01,
        -1.74771014e-01],
       [-2.61422416e+00, -2.54812754e+00,  1.05342808e+00,
      

In [12]:
x_test_pca

array([[ 2.21435735, -0.94903218,  0.95228447,  0.78791127],
       [-2.50659973, -1.8189127 ,  0.45680555,  1.58958192],
       [ 2.12730524,  1.84889911, -0.06650656, -0.53349371],
       [ 2.50886727, -1.2717395 , -0.51542137,  0.84228632],
       [-0.37546624,  0.56631262, -0.61477967, -0.89497518],
       [ 1.36750624, -0.10407461, -5.10950965,  0.49922603],
       [ 2.13754395, -1.51780749, -0.19823085,  0.44985117],
       [-3.03876331, -0.67608136,  0.08506826, -0.70573647],
       [-0.2758078 ,  2.17934109,  0.46001318, -0.79218027],
       [-1.25059924,  2.13272889,  0.03829563, -0.8410568 ],
       [-2.17229537, -0.26937194,  0.90079853, -0.37203801],
       [-4.15065395, -0.59248433,  1.29975265, -0.75852251],
       [ 3.13110267, -2.16664974,  0.51087192, -0.41052281],
       [ 2.34763044,  1.34053226,  0.19375446, -0.70818981],
       [-2.12507456, -1.90448753, -0.74612768,  0.56528037],
       [ 0.85556305,  3.3777156 ,  0.35789025, -0.38500383],
       [ 1.98167335, -1.

In [13]:
explained_variance

array([0.37281068, 0.18739996, 0.10801208, 0.07619859])

In [14]:
pca

PCA(n_components=4)

In [16]:
classifier,Accuracy = navie(x_train_pca,y_train,x_test_pca,y_test)
accnaiv.append(Accuracy)

In [17]:
result = pca_classification(accnaiv)

In [18]:
result

Naive
PCA    1.0

In [19]:
filename = 'Finalized_Naive_Model.sav'

In [20]:
pickle.dump(classifier,open(filename,'wb'))

In [21]:
filenamesc = 'sc.pkl'

In [22]:
pickle.dump(sc,open(filenamesc,'wb'))

In [23]:
sc = pickle.load(open('sc.pkl','rb'))

In [24]:
filenamepca ='pca.pkl'

In [25]:
pickle.dump(pca,open(filenamepca,'wb'))

In [26]:
pca = pickle.load(open('pca.pkl','rb'))

In [27]:
df.columns

Index(['Alcohol', 'Malic_Acid', 'Ash', 'Ash_Alcanity', 'Magnesium',
       'Total_Phenols', 'Flavanoids', 'Nonflavanoid_Phenols',
       'Proanthocyanins', 'Color_Intensity', 'Hue', 'OD280', 'Proline',
       'Customer_Segment'],
      dtype='object')

In [30]:
user_input = ([[14.3,1.71,2.14,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1050]])

In [31]:
scaled_input = sc.transform(user_input)
scaled_input

array([[ 1.62416177, -0.60892585, -0.83215371, -1.11389034,  1.83928074,
         0.88124768,  1.12437858, -0.65926891,  1.13649789,  0.21990142,
         0.39852223,  1.84646357,  0.99340878]])

In [32]:
pca_input = pca.transform(scaled_input)
pca_input

array([[ 3.34882686, -1.08634699,  0.80135407,  0.72474306]])

In [33]:
loaded_model = pickle.load(open('Finalized_Naive_Model.sav','rb'))
Prediction = loaded_model.predict(pca_input)

In [34]:
Prediction

array([1], dtype=int64)