In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
import pickle
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import warnings
warnings.filterwarnings("ignore")

In [2]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        #X_train, X_test, y_train, y_test = train_test_split(indep_X,dep_Y, test_size = 0.25, random_state = 0)
        
        #Feature Scaling
        #from sklearn.preprocessing import StandardScaler
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)        
        return X_train, X_test, y_train, y_test,sc

In [17]:
def cm_prediction(classifier,x_test_pca,y_test):
    y_pred = classifier.predict(x_test_pca)
    
    cm = confusion_matrix(y_test,y_pred)
    Accuracy = accuracy_score(y_test,y_pred)
    Report = classification_report(y_test,y_pred)
    return classifier,Accuracy

In [4]:
# Data Collection

raw_data = pd.read_csv("CKD.csv")
raw_data

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [5]:
df = raw_data
df = pd.get_dummies(df, dtype=int, drop_first=True)# Input Output Split
df

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
indep_x = df.drop('classification_yes',axis = 1)
dep_y = df['classification_yes']

In [7]:
# PCA Model Creation
def pca(x_train,x_test,n):
    pca = PCA(n_components = n)
    x_train_pca = pca.fit_transform(x_train)
    x_test_pca = pca.transform(x_test)
    explained_variance = pca.explained_variance_ratio_
    return x_train_pca, x_test_pca, explained_variance, pca

In [8]:
def random(x_train_pca,y_train,x_test_pca,y_test):
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    classifier.fit(x_train_pca,y_train)
    return cm_prediction(classifier,x_test_pca,y_test)

In [25]:
def pca_classification(accsvmnl):
    pcadataframe = pd.DataFrame(index = ['PCA'], columns = ['Random'])
    pcadataframe['Random'] = accrf
    return pcadataframe

In [10]:
x_train, x_test, y_train, y_test, sc = split_scalar(indep_x,dep_y)

In [11]:
x_train_pca, x_test_pca, explained_variance, pca = pca(x_train,x_test,5)

accrf = []

In [12]:
x_train_pca

array([[-0.25128676,  0.37856611, -1.04857645,  0.49305423, -0.73411699],
       [-1.33765785,  0.50472567,  0.76069328, -0.41795485, -0.50012094],
       [-2.57133641,  0.22793673, -0.16633715,  0.06674013,  0.83886036],
       ...,
       [-0.44615013, -0.46194954,  1.40340525, -0.77930438, -0.16864546],
       [-2.70323719,  0.01339849,  0.23856626,  0.35622769, -0.2581307 ],
       [-2.70561725, -0.13090682, -0.12676888,  0.42533048, -0.0144668 ]])

In [13]:
x_test_pca

array([[-3.43850809e+00,  1.05728920e-01,  3.92571499e-01,
         4.80198055e-01,  4.86657270e-01],
       [ 8.90152029e-01, -7.93922709e-01,  1.56321622e+00,
        -4.65655172e-01,  7.52326225e-01],
       [-2.58112498e+00, -1.52239499e-01, -3.20521000e-01,
         5.76477881e-02,  9.59960776e-02],
       [ 2.05328575e+00, -2.00940148e+00, -2.64930607e+00,
        -1.24477369e+00,  8.50615388e-01],
       [ 7.07553627e-01, -4.41221360e-01,  2.51205502e-01,
         8.32759486e-01, -3.34924544e-01],
       [ 1.01058442e+00, -1.56123328e+00,  3.30008056e+00,
        -1.82135896e-01,  1.28724036e+00],
       [ 5.95275491e+00,  1.23619484e+00,  1.02942655e+00,
        -3.89692134e-01, -6.01043502e-01],
       [ 3.39161184e-01, -2.39169819e+00, -3.12598562e+00,
        -8.86853752e-01,  2.03262764e+00],
       [-2.26284986e+00, -2.79082379e-01,  1.31162076e-01,
        -3.89923085e-01, -4.18157351e-01],
       [-2.81913582e+00,  2.09734580e-01,  8.32884616e-03,
         6.29539849e-01

In [14]:
explained_variance

array([0.25980804, 0.07304735, 0.06507822, 0.05668487, 0.04969609])

In [15]:
pca

PCA(n_components=5)

In [20]:
classifier,Accuracy = random(x_train_pca,y_train,x_test_pca,y_test)
accrf.append(Accuracy)

In [26]:
result = pca_classification(accrf)

In [27]:
result

Random
PCA     1.0

In [28]:
filename = 'Finalized_Random_Model.sav'

In [29]:
pickle.dump(classifier,open(filename,'wb'))

In [31]:
filenamesc = 'sc.pkl'

In [32]:
pickle.dump(sc,open(filenamesc,'wb'))

In [33]:
sc = pickle.load(open('sc.pkl','rb'))

In [34]:
filenamepca ='pca.pkl'

In [35]:
pickle.dump(pca,open(filenamepca,'wb'))

In [36]:
pca = pickle.load(open('pca.pkl','rb'))

In [37]:
df.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [38]:
user_input = ([[5.0,76.58,3.0,0.0,148.11,57.48,6.25,154.3,5.25,12.56,52.0,7700,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0]])

In [39]:
scaled_input = sc.transform(user_input)
scaled_input

array([[-2.92181593e+00,  7.21958125e-03,  1.75526219e+00,
        -3.63175991e-01, -2.53101473e-03, -5.49274524e-02,
         5.25226145e-01,  1.66112329e+00,  3.24646718e-01,
         3.07714193e-02,  1.59044182e+00, -2.40940738e-01,
        -5.69321451e+00,  2.08309522e+00, -5.21862458e-01,
         2.15441626e+00, -1.30410133e-01,  3.87298335e-01,
        -2.01687794e+00,  3.05128577e+00, -2.37775319e-01,
         1.34935344e+00, -7.30296743e-01,  3.38501600e+00,
        -1.95514210e+00,  1.95514210e+00, -4.37304310e-01]])

In [40]:
pca_input = pca.transform(scaled_input)
pca_input

array([[ 2.97743647, -0.47802259,  3.21958171, -0.48058196, -0.61564267]])

In [42]:
loaded_model = pickle.load(open('Finalized_random_Model.sav','rb'))
Prediction = loaded_model.predict(pca_input)

In [43]:
Prediction

array([1])